#!/usr/bin/env python3
"""Write rtl/k054539_tables.svh: MAME's K054539 volume and pan tables in fixed
point, as case statements both Verilator and Quartus read as constants.

MAME (k054539.cpp device_start):
    voltab[i] = 10 ** ((-36 * i / 0x40) / 20) / 4          i = 0..255
    pantab[i] = sqrt(i) / sqrt(0xe)                          i = 0..14
Here both are rounded to Q16 (65536 = 1.0): voltab to 16 bits (<= 16384),
pantab to 17 (65536 at i = 14).  The channel gain MAME computes in double
precision is then (voltab * pantab) >> 16, a relative error under 1e-4 --
inaudible, and the sound gate compares band energy, not samples.
"""
import math, os
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
vol = [round(10 ** ((-36.0 * i / 0x40) / 20.0) / 4.0 * 65536) for i in range(256)]
pan = [round(math.sqrt(i) / math.sqrt(0xe) * 65536) for i in range(15)]
with open(os.path.join(root, 'rtl', 'k054539_tables.svh'), 'w') as f:
    f.write('// generated by tools/gen_k054539_tables.py -- do not edit\n')
    f.write('function automatic [15:0] k539_vol(input [7:0] i);\n    case (i)\n')
    for i, v in enumerate(vol):
        f.write(f"        8'd{i}: k539_vol = 16'd{v};\n")
    f.write("        default: k539_vol = 16'd0;\n    endcase\nendfunction\n")
    f.write('function automatic [16:0] k539_pan(input [3:0] i);\n    case (i)\n')
    for i, v in enumerate(pan):
        f.write(f"        4'd{i}: k539_pan = 17'd{v};\n")
    f.write("        default: k539_pan = 17'd0;\n    endcase\nendfunction\n")
print('voltab[0]', vol[0], 'voltab[0x40]', vol[0x40], 'pantab[14]', pan[14])
